spring.application.name=consumidor-horarios

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Puerto del microservicio
server.port=8084

# Oracle Cloud ADB (usa cn1_tp)
spring.datasource.url=jdbc:oracle:thin:@cn1_high?TNS_ADMIN=C:/Users/ariel/Desktop/Wallet_CN1
spring.datasource.username=ADMIN
spring.datasource.password=Arieliwis10.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.oracle.net.ssl_server_dn_match=true
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=C:/Users/ariel/Desktop/Wallet_CN1
spring.datasource.hikari.data-source-properties.oracle.net.ssl_version=1.2

